[project]
name = 'airdrop'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[contracts.nft]
path = 'contracts/nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.proxy]
path = 'contracts/proxy.clar'
clarity_version = 2
epoch = 2.5

[contracts.external-proxy]
path = 'contracts/proxy.clar'
deployer = "wallet_1"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
