name: Test

on:
  push:
    paths:
      - "contracts/**"
      - "tests/**"
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'BitcoinFaces' }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run test
